### ISSUE TITLE
Riso.image fill not working

### ISSUE THREAD

**Issue by fgmnts** [antiboredom/p5.riso#12]
When I try the Riso.image example, no matter if I use `orange.fill(200);` of  `orange.fill(0);` I get the same result.

According to the docs this should work: [code](https://antiboredom.github.io/p5.riso/#image)

[Link to the example of issue](https://editor.p5js.org/fgmnts/sketches/kJ4x-HG_)

**Comment by antiboredom** [comment]
This is definitely a bug - looking into it now...

**Comment by antiboredom** [comment]
Hi @fgmnts - I believe this should be fixed now - make sure to [update your copy of p5riso](https://raw.githubusercontent.com/antiboredom/p5.riso/master/lib/p5.riso.js) from the repo, and give it another try!
