### ISSUE TITLE
Does not work in instance mode

### ISSUE THREAD

**Issue by notwaldorf** [antiboredom/p5.riso#14]
Thank you so much for this library! It's so great!

I tried to use it in instance mode and couldn't, since the library assumes everything is in global mode. I've patched together a local copy that uses a passed in instance, but I think the constructor API is technically a breaking change (needs a new parameter) so I didn't want to send a PR unless you wanted this. Let me know if I should!

**Comment by notwaldorf** [comment]
Oh, I guess the API could stay the same if the library relied on a property like 'window.p5Instance' to be set.

**Comment by antiboredom** [comment]
Thanks for this - looking great!
