### ISSUE TITLE
Examples for extractRGBChannel and extractCMYKChannel functions not working

### ISSUE THREAD

**Issue by acolle** [antiboredom/p5.riso#16]
I'm trying to run the examples for the extractRGBChannel and extractCMYKChannel functions given on the website but it seems that the `draw` function does not do anything. Is it a faulty behaviour ? Is the function the same as using the `image` function (see comment in the code below)?

**Reproduce the issue**
Use the following code in the web editor to reproduce the issue:

```
let img_url = "https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80";
 
let img;

function preload() {
  img = loadImage(img_url);
}

function setup() {
  // from the website   
  createCanvas(500, 500);
  let blue = new Riso("blue");
  let red = new Riso("red");
 
  let justBlues = extractRGBChannel(img, "blue"); //extract blue from img
  let justReds = extractRGBChannel(img, "red"); //extract red from img
  
  // these 2 functions does not seem to display anything
  blue.draw(justBlues); //draw justblues to blue layer
  red.draw(justReds); //draw justred to red layer
  
  // is the first function above similar to the one below?
  //blue.image(justBlues, 0, 0);
  
  drawRiso();
}
```

Many thanks for the the library. It's a lot of fun using it 😃

**Comment by antiboredom** [comment]
Hi! It looks like the documentation is wrong for that function on the website!! It should work if you switch this:

```javascript
blue.draw(justBlues); //draw justblues to blue layer
red.draw(justReds); //draw justred to red layer
```

to:

```javascript
blue.image(justBlues, 0, 0); 
red.image(justReds, 0, 0);
```

I'll go ahead and update the site...

**Comment by acolle** [comment]
Thanks for the prompt answer! I can see the code has been updated on the website for the extractRGBChannel example but not the extractCMYKChannel example just below. Just so you know 😃

**Comment by antiboredom** [comment]
oops!!!! thanks again - will fix that now...
