### ISSUE TITLE
Cant get examples to work that arent using images 

### ISSUE THREAD

**Issue by eadehemingway** [antiboredom/p5.riso#19]
I am so excited to use this library, thank you so much for making it!

I'm not sure if I am missing something but it seems lots of examples dont work in the p5 editor (or when I recreate the examples locally) e.g:

- https://github.com/antiboredom/p5.riso/tree/master/examples/Cutout

<img width="584" alt="Screenshot 2021-12-19 at 15 41 44" src="https://user-images.githubusercontent.com/32163243/146681147-497f9e8b-2d63-4f8e-b61a-6f2671580f51.png">

- https://github.com/antiboredom/p5.riso/tree/master/examples/Color_test 

<img width="620" alt="Screenshot 2021-12-19 at 15 42 16" src="https://user-images.githubusercontent.com/32163243/146681162-0c95c79f-c976-4309-8afd-a00ae3b08d80.png">

- https://github.com/antiboredom/p5.riso/tree/master/examples/Smudge 

<img width="744" alt="Screenshot 2021-12-19 at 15 43 20" src="https://user-images.githubusercontent.com/32163243/146681195-513ef2df-8ea4-47f0-9a38-b6af3e77d439.png">

Have I missed something? 
thanks!

**Comment by antiboredom** [comment]
Hi - can you share a link to the p5 editor sketches that aren't working so I can take a look?

**Comment by eadehemingway** [comment]
Hi, yeah they are just the links linked in the above links, they are:
- https://editor.p5js.org/brain/sketches/GpuJH1Zur
- https://editor.p5js.org/brain/sketches/rCdUW72sC
- https://editor.p5js.org/brain/sketches/i1gDFtMAI
And also this one seems to be broken for a different reason: 
- https://editor.p5js.org/brain/sketches/wLGAPKEMk
thanks!

**Comment by antiboredom** [comment]
That’s odd - all of these seem to be working for me, except for the last one. Are you seeing any errors? Also what browser are you using?

**Comment by eadehemingway** [comment]
ooh how odd, I am using google chrome... The first three all work in the sense that I can see the shapes but they dont work in the sense that they dont have the riso effect (as shown in the screenshots above). What browser are you using?

**Comment by antiboredom** [comment]
Ah - I see what you mean. The library doesn't actually generate a riso effect, it's intended to prepare files for riso printing, and to preview what the final prints might look like. The images that we have are scans of actual riso prints that we've made using the library, rather than screen shots. I think we could do more work in the documentation to clarify this. Sorry for the confusion!

**Comment by eadehemingway** [comment]
oh I see! thanks for the clarification, that makes sense now!
