### ISSUE TITLE
extractmappedchannels

### ISSUE THREAD

**Issue by tegacodes** [antiboredom/p5.riso#22]
If the riso sketches aren't called with a background function, and the p5 editor is set in dark mode, the background seems black as pixels are transparent I guess?

If you turn off the background and change to dark mode, these sketches look really different. lol. Not sure if this is a bug, but perhaps we should have the background default to white on the canvas if it is not called?

https://editor.p5js.org/brain/sketches/4NEc8FlAF
https://editor.p5js.org/brain/sketches/hCugQlVd1

**Comment by antiboredom** [comment]
I think this *isn't* a bug since the same issue would occur if you were making any sketch without a background color. I do think though that we should make sure that all examples have a background(255) in either their setup or draw functions...
