### ISSUE TITLE
TypeError: this._curElement is undefined (p5.riso: line 104)

### ISSUE THREAD

**Issue by bmoren** [antiboredom/p5.riso#9]
Getting this export error while trying to do something rather complex. looping over an object that is drawing with begin/end shape.

Does this seem like an issue in the Library. I really cant tell, but I've not run into any issues yet with similar types of sketches that don't instantiate a class.

<img width="425" alt="Screen Shot 2019-09-27 at 10 44 52 AM" src="https://user-images.githubusercontent.com/1385996/65783022-82b4e700-e114-11e9-82d2-c54e51ae2126.png">

the sketch in question: https://editor.p5js.org/benmoren/sketches/EhMoKa5zH

something similar which is fine: https://editor.p5js.org/benmoren/sketches/z_C5L0b-q

**Comment by antiboredom** [comment]
Hi - it looks like the noiseloop sketch is using an older version of p5 (0.7.2) and the working sketch is using 0.9.0. When I update noiseloop to 0.9.0 everything seems to work. I'm going to close this for now, but if I'm missing something please re-open!
